### ISSUE TITLE
Typo on Lecture 2

### ISSUE THREAD

**Issue by yh36** [cpeikert/LatticesInCryptography#1]
In the section of Gram-Schmidt Orthogonalization,
![image](https://github.com/cpeikert/LatticesInCryptography/assets/11954016/8ebd5724-6dcf-44a0-ae64-89d6117e3f64)

BTW, do we have video recording available to students that are not from University of Michigan? I'm really interested in the post-quantum cryptography. It will be better if I can get access to the course recording for personal use.

Thanks!

**Comment by cpeikert** [comment]
Thank you! This is fixed in the latest commit.

Unfortunately, I do not think the recordings are available outside U-Michigan.
